### ISSUE TITLE
微信读书的在线书籍的获取是否异常？

### ISSUE THREAD

**Issue by deckvig** [OldPanda/douban-book-plus-homepage#1]
https://book.douban.com/subject/36096578/

这本书在微信读书可读，但是看起来插件检测不到
![CleanShot 2023-12-10 at 00 32 32@2x](https://github.com/OldPanda/douban-book-plus-homepage/assets/15033627/f6c7908b-c3bc-40f8-b8af-b4d0f1f52de6)
![CleanShot 2023-12-10 at 00 33 03@2x](https://github.com/OldPanda/douban-book-plus-homepage/assets/15033627/6d75d9b3-0eb0-4ee5-a894-da4a3fc63811)

**Comment by OldPanda** [comment]
@deckvig 谢谢反馈！这确实是插件的问题，估计是书籍的匹配做得不够好

**Comment by OldPanda** [comment]
这个问题已在 1.3.1 版本中修复，谢谢使用！
