### ISSUE TITLE
开发建议

### ISSUE THREAD

**Issue by honwhy** [OldPanda/douban-book-plus-homepage#10]
- 建议使用wxt.dev框架开发，可以兼容v3和v2，一套代码同时支持chrome和firefox
- 为啥这本书https://book.douban.com/subject/36518892/ 没有搜索到微信读书的结果

**Comment by OldPanda** [comment]
> 建议使用wxt.dev框架开发，可以兼容v3和v2，一套代码同时支持chrome和firefox

谢谢您的建议，我也在考虑使用 [wxt.dev](https://wxt.dev/) 重写一遍这个插件，便于后续的开发维护，只是最近实在没有时间去做这件事。

> 为啥这本书 https://book.douban.com/subject/36518892/ 没有搜索到微信读书的结果

这是因为两个网站的图书信息并不是完全匹配的，这个问题已经修复，谢谢您的支持，祝使用愉快！
