### ISSUE TITLE
插件是否已经失效了

### ISSUE THREAD

**Issue by psk107520** [OldPanda/douban-book-plus-homepage#12]
![Uploading 111.png…]()

**Comment by OldPanda** [comment]
<img width="1081" alt="image" src="https://github.com/OldPanda/douban-book-plus-homepage/assets/2587202/aefe58d7-540f-471c-b8c5-4acf62ca2ee2">
我这里显示正常，请问您是在哪个页面上发现了问题？

**Comment by psk107520** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信已收到，我会尽快联系你

**Comment by psk107520** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，来信已收到，我会尽快联系你
