### ISSUE TITLE
goodreads.com寻求支持同样的功能

### ISSUE THREAD

**Issue by chenjunqiang** [OldPanda/douban-book-plus-homepage#14]
goodreads.com寻求支持同样的功能

谢谢老板开发的插件，很有用，有些书籍，特别是繁体书，和英文书，goodreads更好用，方便更新一版本支持下吗？谢谢老板

**Comment by OldPanda** [comment]
你是说在 [Goodreads](https://www.goodreads.com/) 上显示电子书资源？但这款插件名字叫 “Douban Book+” ，支持其他网站似乎不妥，不过可以考虑专门出一款插件在各种书籍网站上显示其他可能有的资源

**Comment by TonyYanOnFire** [comment]
没必要囿于插件名称而不去拓展其适用范围。我也期待 goodreads 和 Amazon 等的支持.
