### ISSUE TITLE
插件部分失效

### ISSUE THREAD

**Issue by wzaiz** [OldPanda/douban-book-plus-homepage#15]
插件在多个书籍页面无法生效，如图为其中之一
![image](https://github.com/OldPanda/douban-book-plus-homepage/assets/82254937/5829d8c2-db20-4104-b24a-4fbfc9299fc1)

**Comment by OldPanda** [comment]
这是因为没有找到这本书的电子版，这块的用户体验还有待于改善

**Comment by OldPanda** [comment]
问题已解决
<img width="1099" alt="image" src="https://github.com/OldPanda/douban-book-plus-homepage/assets/2587202/a8e5566d-1823-47e5-bdc3-37fdb1d7916e">
