### ISSUE TITLE
Edge插件，GetEBookUrls接口报错

### ISSUE THREAD

**Issue by wqiuming** [OldPanda/douban-book-plus-homepage#16]
![image](https://github.com/OldPanda/douban-book-plus-homepage/assets/29088495/eddced2d-2873-4cf1-8f27-66fe76dd3849)
![image](https://github.com/OldPanda/douban-book-plus-homepage/assets/29088495/5689193f-895b-4b12-be29-844279c524f1)
![image](https://github.com/OldPanda/douban-book-plus-homepage/assets/29088495/1ca506a0-b126-45b8-a660-b38b5045b2db)

**Comment by OldPanda** [comment]
我没有在 Edge 上成功复现这个问题，或许你可以尝试刷新页面或者重新安装插件
<img width="1054" alt="image" src="https://github.com/OldPanda/douban-book-plus-homepage/assets/2587202/f9490e4a-5be9-44fd-8bc7-8a784438a45d">

**Comment by wqiuming** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wqiuming** [comment]
sorry，安装插件权限没勾上，不好意思，勾上权限就好了。打扰了，再次抱歉~
![image](https://github.com/OldPanda/douban-book-plus-homepage/assets/29088495/13fdad46-11cb-4f2a-84fc-9b425f27b982)
