### ISSUE TITLE
[建议] 没有找到书籍时进行相应提示

### ISSUE THREAD

**Issue by TonyYanOnFire** [OldPanda/douban-book-plus-homepage#17]
现状: 没有找到书籍时没有任何UI提示, 就像插件没安装一样

改进建议: 没有找到书籍时,"在线阅读"的UI元素也显示, 只是没有选项, 或提示"未找到"

理由: 进行明确反馈, 提高用户预期

**Comment by OldPanda** [comment]
谢谢建议，更新的进度会在[这里](https://github.com/OldPanda/douban-book-plus-homepage/issues/15)跟踪
