### ISSUE TITLE
微信读书数据部分异常

### ISSUE THREAD

**Issue by deckvig** [OldPanda/douban-book-plus-homepage#23]
![CleanShot 2024-04-22 at 22 58 27@2x](https://github.com/OldPanda/douban-book-plus-homepage/assets/15033627/b10463a4-3975-4f8a-bd26-bbfffd6f1ef6)

这本书在插件中无法识别到微信读书的链接

豆瓣：https://book.douban.com/subject/36449803/

微信读书：https://weread.qq.com/web/bookDetail/74332a90813ab86c4g019d98

**Comment by OldPanda** [comment]
谢谢反馈！这个问题已在近日修复，祝使用愉快！
<img width="1081" alt="image" src="https://github.com/OldPanda/douban-book-plus-homepage/assets/2587202/f3ce91b4-d13e-4a8a-9904-a8516985d8f3">
