### ISSUE TITLE
Douban Book+ 未成功匹配特定书籍

### ISSUE THREAD

**Issue by gandli** [OldPanda/douban-book-plus-homepage#6]
### 问题描述
当访问豆瓣读书页面（例如《Python编程（第3版）》：https://book.douban.com/subject/36365320/  ）时，Douban Book+ 扩展未能成功匹配并显示在线资源链接。

### 预期行为
通常，Douban Book+ 应该在页面上显示指向在线资源（如Z-Library）的链接。

### 实际行为
在上述提到的书籍页面，扩展没有显示任何在线资源链接。然而，使用ISBN“9787115613639”在Z-Library（链接：https://zh.singlelogin.re/s/9787115613639?extensions%5B%5D=EPUB&order=date  ）可以找到这本书的电子版。

### 可能的问题
似乎扩展在匹配书籍时存在问题。可能是因为它无法正确解析豆瓣页面的信息，或者是数据匹配逻辑的问题。

### 重现步骤
1. 打开豆瓣读书页面《Python编程（第3版）》：https://book.douban.com/subject/36365320/
2. 观察Douban Book+扩展是否显示在线资源链接。

### 环境信息
- 浏览器：Google Chrome 120.0.6099.216
- 扩展版本：Douban Book+ 1.4.0

**Comment by OldPanda** [comment]
谢谢详细的问题描述，应该是书籍标题的匹配问题，我尽快修一下

**Comment by OldPanda** [comment]
这个问题刚刚修复了，祝使用愉快！
<img width="1083" alt="image" src="https://github.com/OldPanda/douban-book-plus-homepage/assets/2587202/eb1ecf50-c6e9-478e-a401-9a4c298e7945">
